import type { Metadata } from "next";
import { Montserrat, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { RootLayoutProps } from "@/types";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight:['400','500','600','700','800','900'],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  subsets: ["latin"],
  weight:['400','500','600','700'],
});

export const metadata: Metadata = {
  title: "My stream",
  description: "Generated by create next app",
};

export default function RootLayout({children}:RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${spaceGrotesk.variable} antialiased`}
      >
 
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
       <ClerkProvider>{children}</ClerkProvider>
          </ThemeProvider>
    
      </body>
    </html>
  );
}
